from __future__ import annotations

from contextlib import suppress
from typing import Literal
from warnings import warn

import matplotlib.pyplot as plt
import numpy as np
import xarray as xr
from scipy.integrate import trapezoid

from ..utils import get_opensees_module
from ._smart_analyze import SmartAnalyze

ops = get_opensees_module()

Axis = Literal["y", "z"]
CapacityMode = Literal["peak", "peakdrop", "strain", "curvature", "manual"]


class MomentCurvature:
    """Moment-curvature analysis and approximate N-My-Mz interaction for fiber sections.

    The section materials and fiber section must be defined in OpenSeesPy before
    creating or running this object.  The analysis model is a two-node
    ``zeroLengthSection`` element with axial load applied first and held
    constant, followed by displacement-control curvature loading about the
    requested bending axis.

    Sign conventions follow OpenSeesPy:

    - ``axial_force < 0`` means compression.
    - ``axis="y"`` controls rotational DOF 5 and returns the load factor of a
      unit moment about the local y-axis.
    - ``axis="z"`` controls rotational DOF 6 and returns the load factor of a
      unit moment about the local z-axis.
    - Fiber data columns are ``yloc, zloc, area, mat, stress, strain``.

    Parameters
    ----------
    sec_tag : int
        Tag of a previously defined fiber section.
    axial_force : float, optional
        Constant axial load. Compression is negative.

    Attributes
    ----------
    phi : numpy.ndarray or None
        Curvature history after :meth:`analyze`.
    M : numpy.ndarray or None
        Moment history after :meth:`analyze`.
    FiberData : numpy.ndarray or None
        Fiber response history with shape ``(n_step, n_fiber, 6)``.
    cycle_path : numpy.ndarray or None
        Target curvature path used when ``cycle_analyze=True``.
    NMMresult : dict
        Result dictionary generated by :meth:`build_NMM`.

    Examples
    --------
    >>> mc = MomentCurvature(sec_tag=1, axial_force=-500e3)
    >>> mc.analyze(axis="y", max_phi=0.05, incr_phi=1e-4)
    >>> phi, moment = mc.get_M_phi()
    >>> phi_u, moment_u = mc.get_limit_state(matTag=1, threshold=-0.003)
    """

    def __init__(self, sec_tag: int, axial_force: float = 0) -> None:
        self.P = float(axial_force)
        self.sec_tag = int(sec_tag)
        self.phi: np.ndarray | None = None
        self.M: np.ndarray | None = None
        self.FiberData: np.ndarray | None = None
        self.cycle_path: np.ndarray | None = None
        self.NMMresult: dict[str, np.ndarray | str] = {}

    def new(self, sec_tag: int, axial_force: float = 0) -> MomentCurvature:
        """Reset the object for another section or axial load.

        This clears all stored analysis results, cyclic path data and NMM
        results, then returns ``self`` so calls can be chained.

        Parameters
        ----------
        sec_tag : int
            Tag of a previously defined fiber section.
        axial_force : float, optional
            Constant axial load. Compression is negative.

        Returns
        -------
        MomentCurvature
            The same object after reinitialization.
        """
        self.P = float(axial_force)
        self.sec_tag = int(sec_tag)
        self.phi = None
        self.M = None
        self.FiberData = None
        self.cycle_path = None
        self.NMMresult = {}
        return self

    def analyze(
        self,
        axis: Axis = "y",
        max_phi: float = 0.05,
        incr_phi: float = 1e-4,
        limit_peak_ratio: float = 0.8,
        cycle_analyze: bool = False,
        smart_analyze: bool = True,
        debug: bool = False,
    ) -> None:
        """Run the moment-curvature analysis.

        Results are stored in ``phi``, ``M`` and ``FiberData``.  The analysis
        terminates when the requested curvature is reached, or when the
        post-peak moment has dropped below ``limit_peak_ratio`` with unloading
        slope reversal.

        Parameters
        ----------
        axis : {"y", "z"}, optional
            Bending axis. ``"y"`` controls DOF 5; ``"z"`` controls DOF 6.
        max_phi : float, optional
            Target maximum curvature. The sign sets the monotonic loading
            direction. For cyclic analysis, this is replaced by the maximum
            absolute value in ``cycle_path``.
        incr_phi : float, optional
            Nominal curvature increment used to discretize the loading path.
        limit_peak_ratio : float, optional
            Stop ratio after peak moment. For example, ``0.8`` stops after a
            20 percent strength drop once the response is descending.
        cycle_analyze : bool, optional
            If ``True``, use the path created by :meth:`set_cycle_path`.
        smart_analyze : bool, optional
            If ``True``, use :class:`SmartAnalyze` to retry failed steps with
            alternate algorithms and step relaxation.
        debug : bool, optional
            If ``True``, print OpenSees convergence details.

        Notes
        -----
        Existing OpenSees nodes/elements are reused when present.  Analysis
        patterns and time series with tags 1 and 2 are removed before the new
        run, so avoid using those tags for unrelated loads during this helper.
        """
        self.phi, self.M, self.FiberData = _analyze(
            sec_tag=self.sec_tag,
            P=self.P,
            axis=axis,
            max_phi=max_phi,
            incr_phi=incr_phi,
            stop_ratio=limit_peak_ratio,
            cycle=cycle_analyze,
            cycle_path=self.cycle_path,
            smart_analyze=smart_analyze,
            need_resp=True,
            debug=debug,
        )
        print("MomentCurvature: analysis complete.")

    def set_cycle_path(self, max_phi: float, n_cycle: int = 20, n_hold: int = 1) -> np.ndarray:
        """Build a symmetric incrementally growing cyclic curvature path.

        The generated path starts at zero, alternates positive and negative
        target curvatures with increasing amplitude, and returns to zero.  It
        is stored in ``cycle_path`` and used by :meth:`analyze` when
        ``cycle_analyze=True``.

        Parameters
        ----------
        max_phi : float
            Peak absolute curvature. The sign is ignored.
        n_cycle : int, optional
            Number of amplitude levels including zero. Must be at least 2.
        n_hold : int, optional
            Number of repetitions for each positive/negative amplitude pair.

        Returns
        -------
        numpy.ndarray
            Curvature target sequence, including the initial and final zero.
        """
        if n_cycle < 2:
            raise ValueError("n_cycle must be >= 2.")  # noqa: TRY003
        if n_hold < 1:
            raise ValueError("n_hold must be >= 1.")  # noqa: TRY003

        max_phi = abs(float(max_phi))
        upper = np.linspace(0.0, max_phi, int(n_cycle))[1:]
        below = np.linspace(0.0, -max_phi, int(n_cycle))[1:]
        pattern = [0.0]
        for up, low in zip(upper, below):
            for _ in range(int(n_hold)):
                pattern.extend([float(up), float(low)])
        pattern.append(0.0)
        self.cycle_path = np.asarray(pattern, dtype=float)
        return self.cycle_path.copy()

    setCyclePath = set_cycle_path

    def plot_M_phi(self, ax=None):
        """Plot the moment-curvature relationship.

        Parameters
        ----------
        ax : matplotlib.axes.Axes, optional
            Axes to draw on. A new figure and axes are created when omitted.

        Returns
        -------
        matplotlib.axes.Axes
            Axes containing the plot.
        """
        self._require_result()
        lw = 0.8 if self.cycle_path is not None else 1.5
        if ax is None:
            _, ax = plt.subplots(1, 1, figsize=(8, 5))
        ax.plot(self.phi, self.M, lw=lw, c="blue")
        ax.set_title("$M-\\phi$", fontsize=18)
        ax.set_xlabel("$\\phi$", fontsize=14)
        ax.set_ylabel("$M$", fontsize=14)
        ax.grid(True)
        return ax

    plotMPhi = plot_M_phi

    def plot_fiber_responses(
        self,
        matTag: int | list[int] | np.ndarray | None = None,
        line_width: float = 0.7,
        max_fibers: int | float = np.inf,
        sharex: bool = False,
        sharey: bool = False,
        return_ax: bool = False,
    ):
        """Plot fiber stress-strain histories.

        Parameters
        ----------
        matTag : int or array-like, optional
            Material tag or tags to plot. When omitted, all material tags found
            in the final fiber state are plotted.
        line_width : float, optional
            Width of each stress-strain curve.
        max_fibers : int or float, optional
            Maximum number of fibers plotted per material tag. Large fiber
            groups are uniformly subsampled for readability.
        sharex, sharey : bool, optional
            Share subplot x or y limits.
        return_ax : bool, optional
            If ``True``, return the axes array. Otherwise return ``None``.

        Returns
        -------
        numpy.ndarray or None
            Matplotlib axes when ``return_ax=True``.
        """
        self._require_result()
        fiber_data = self.FiberData
        tags = np.unique(fiber_data[-1, :, 3]) if matTag is None else np.atleast_1d(matTag).astype(float)
        _, axs = plt.subplots(len(tags), 1, figsize=(8, 3 * len(tags)), squeeze=False, sharex=sharex, sharey=sharey)
        axs = axs.ravel()

        for tag, ax in zip(tags, axs):
            idxs = np.flatnonzero(np.abs(fiber_data[-1, :, 3] - tag) < 1e-6)
            if idxs.size == 0:
                warn(f"matTag {tag:g} not found; skipped.", stacklevel=2)
                continue
            if np.isfinite(max_fibers) and idxs.size > int(max_fibers):
                keep = np.linspace(0, idxs.size - 1, int(max_fibers), dtype=int)
                idxs = idxs[keep]
            ax.plot(fiber_data[:, idxs, 5], fiber_data[:, idxs, 4], lw=line_width)
            ax.set_title(f"matTag = {tag:g}, nFiber = {idxs.size}", fontsize=13)
            ax.set_xlabel("Strain", fontsize=12)
            ax.set_ylabel("Stress", fontsize=12)
            ax.grid(True)
        plt.tight_layout()
        if return_ax:
            return axs
        return None

    def get_phi(self) -> np.ndarray:
        """Return the curvature history from the latest analysis."""
        self._require_result()
        return self.phi

    def get_curvature(self) -> np.ndarray:
        """Return the curvature history from the latest analysis."""
        return self.get_phi()

    getCurvature = get_curvature

    def get_M(self) -> np.ndarray:
        """Return the moment history from the latest analysis."""
        self._require_result()
        return self.M

    def get_moment(self) -> np.ndarray:
        """Return the moment history from the latest analysis."""
        return self.get_M()

    getMoment = get_moment

    def get_M_phi(self) -> tuple[np.ndarray, np.ndarray]:
        """Return ``(curvature, moment)`` arrays from the latest analysis."""
        self._require_result()
        return self.phi, self.M

    getMPhi = get_M_phi

    def get_fiber_data(self) -> xr.DataArray:
        """Return all fiber response data as an ``xarray.DataArray``.

        Returns
        -------
        xarray.DataArray
            Data with dimensions ``Steps``, ``Fibers`` and ``Properties``.
            The properties are ``yloc``, ``zloc``, ``area``, ``mat``,
            ``stress`` and ``strain``.
        """
        self._require_result()
        return xr.DataArray(
            self.FiberData,
            coords={
                "Steps": np.arange(len(self.FiberData)),
                "Fibers": np.arange(len(self.FiberData[0])),
                "Properties": ["yloc", "zloc", "area", "mat", "stress", "strain"],
            },
            dims=("Steps", "Fibers", "Properties"),
            name="FiberData",
        )

    def get_limit_state(
        self,
        matTag: int | list[int] | np.ndarray = 1,
        threshold: float | list[float] | np.ndarray = 0.0,
        peak_drop: float | bool = False,
        return_index: bool = False,
    ):
        """Return curvature and moment at a limit state.

        Two limit-state modes are supported:

        - Strain-threshold mode, used when ``peak_drop=False``.  The first
          step is selected where any fiber of the requested material reaches
          its strain threshold.
        - Peak-drop mode, used when ``peak_drop`` is ``True`` or a float.  The
          first post-peak step is selected where ``abs(M)`` has dropped by the
          requested fraction.

        Parameters
        ----------
        matTag : int or array-like, optional
            Material tag or tags monitored in strain-threshold mode.
        threshold : float or array-like, optional
            Strain threshold for each material tag. A positive value monitors
            tensile strain with ``max(strain) >= threshold``. A negative value
            monitors compressive strain with ``min(strain) <= threshold``. A
            scalar threshold is broadcast to multiple material tags.
        peak_drop : bool or float, optional
            If ``False``, use strain-threshold mode. If ``True``, use a default
            20 percent post-peak drop. If a float, it must be the drop fraction
            in ``(0, 1)``; for example ``0.3`` means a 30 percent drop from
            peak strength.
        return_index : bool, optional
            If ``True``, also return the zero-based result index.

        Returns
        -------
        tuple
            ``(phi_u, M_u)`` or ``(phi_u, M_u, index)``.
        """
        self._require_result()
        if peak_drop is not False:
            drop = 0.20 if peak_drop is True else float(peak_drop)
            moment, idx = _extract_moment_capacity(
                self.phi,
                self.M,
                self.FiberData,
                cap_mode="peakdrop",
                peak_drop=drop,
                mat_tag=matTag,
                threshold=threshold,
            )
        else:
            moment, idx = _extract_moment_capacity(
                self.phi,
                self.M,
                self.FiberData,
                cap_mode="strain",
                mat_tag=matTag,
                threshold=threshold,
            )
        result = (float(self.phi[idx]), float(moment))
        if return_index:
            return (*result, int(idx))
        return result

    getLimitState = get_limit_state

    def bilinearize(self, phiy: float, My: float, phiu: float, plot: bool = False, ax=None):
        """Compute an equal-area bilinear approximation.

        The initial elastic stiffness ``k = My / phiy`` is preserved.  The
        equivalent yield point is chosen so the bilinear curve has the same
        area as the actual moment-curvature curve up to ``phiu``.  Positive
        and negative loading branches are both supported.

        Parameters
        ----------
        phiy : float
            Initial yield curvature. Must be nonzero.
        My : float
            Initial yield moment. Must be nonzero.
        phiu : float
            Ultimate or target curvature used as the integration end point.
            The sign selects the loading branch.
        plot : bool, optional
            If ``True``, draw the original branch and bilinear curve.
        ax : matplotlib.axes.Axes, optional
            Axes used when ``plot=True``.

        Returns
        -------
        tuple[float, float]
            Equivalent yield curvature and moment ``(phi_eq, M_eq)``.
        """
        self._require_result()
        phi_eq, m_eq, idx_u = _bilinearize(self.phi, self.M, phiy, My, phiu)

        if plot:
            ax = _plot_bilinear(self.phi, self.M, phiy, My, phiu, phi_eq, m_eq, idx_u, ax=ax)
            # return phi_eq, m_eq, idx_u, ax
        return phi_eq, m_eq

    def build_NMM(
        self,
        NList: np.ndarray | list[float] | None = None,
        axis1: Axis = "y",
        axis2: Axis = "z",
        phiMax: float = 0.05,
        incrPhi: float = 1e-4,
        nTheta: int = 36,
        limitPeakRatio: float = 0.8,
        smartAnalyze: bool = True,
        useParallel: bool = False,
        capacityMode: CapacityMode = "peak",
        peakDrop: float = 0.20,
        matTag: int | list[int] | np.ndarray = 1,
        threshold: float | list[float] | np.ndarray = 0.0,
        targetPhi: float | None = None,
        MyCapManual: np.ndarray | list[float] | None = None,
        MzCapManual: np.ndarray | list[float] | None = None,
        debug: bool = False,
    ) -> dict[str, np.ndarray | str]:
        """Build an approximate N-My-Mz interaction surface.

        For each axial load, capacities about ``axis1`` and ``axis2`` are
        obtained from uniaxial moment-curvature analyses.  The biaxial contour
        is then generated from the ellipse equation
        ``(My/MyCap)^2 + (Mz/MzCap)^2 = 1``.

        Parameters
        ----------
        NList : array-like, optional
            Axial load levels. Compression should be negative.
        axis1, axis2 : {"y", "z"}, optional
            Bending axes used to obtain the two uniaxial capacities.
        phiMax : float, optional
            Maximum curvature for each uniaxial analysis.
        incrPhi : float, optional
            Curvature increment for each uniaxial analysis.
        nTheta : int, optional
            Number of angular divisions around each My-Mz contour. The stored
            contour is closed, so ``My`` and ``Mz`` have ``nTheta + 1`` columns.
        limitPeakRatio : float, optional
            Stop ratio passed to each uniaxial analysis.
        smartAnalyze : bool, optional
            Use :class:`SmartAnalyze` during the uniaxial analyses.
        useParallel : bool, optional
            Accepted for MATLAB API compatibility. OpenSeesPy uses one global
            interpreter, so this implementation runs sequentially.
        capacityMode : {"peak", "peakdrop", "strain", "curvature", "manual"}, optional
            Rule used to extract each uniaxial capacity.
        peakDrop : float, optional
            Drop fraction for ``capacityMode="peakdrop"``.
        matTag, threshold : int or array-like, optional
            Material tags and strain thresholds for ``capacityMode="strain"``.
        targetPhi : float, optional
            Curvature used for ``capacityMode="curvature"``.
        MyCapManual, MzCapManual : array-like, optional
            User-supplied capacities for ``capacityMode="manual"``. Each must
            have the same length as ``NList``.
        debug : bool, optional
            Print convergence details during uniaxial analyses.

        Returns
        -------
        dict
            Result dictionary stored in ``NMMresult`` with keys ``N``, ``My``,
            ``Mz``, ``thetas``, ``MyCap``, ``MzCap`` and ``capMode``.

        Notes
        -----
        The NMM surface is an engineering approximation based on elliptical
        interpolation between two uniaxial capacities at each axial load.  It
        is not a full biaxial nonlinear section analysis.
        """
        if NList is None:
            NList = np.linspace(-1e6, 0.0, 8)
        n_list = np.asarray(NList, dtype=float).reshape(-1)
        if n_list.size == 0:
            raise ValueError("NList must not be empty.")  # noqa: TRY003
        if int(nTheta) < 4:
            raise ValueError("nTheta must be >= 4.")  # noqa: TRY003
        if useParallel:
            warn(
                "useParallel=True is accepted for MATLAB API compatibility but is not used by OpenSeesPy.", stacklevel=2
            )

        cap_mode = _normalize_capacity_mode(capacityMode)
        if cap_mode == "manual":
            if MyCapManual is None or MzCapManual is None:
                raise ValueError("MyCapManual and MzCapManual are required when capacityMode='manual'.")  # noqa: TRY003
            my_cap = np.abs(np.asarray(MyCapManual, dtype=float).reshape(-1))
            mz_cap = np.abs(np.asarray(MzCapManual, dtype=float).reshape(-1))
            if my_cap.size != n_list.size or mz_cap.size != n_list.size:
                raise ValueError("MyCapManual and MzCapManual must match the length of NList.")  # noqa: TRY003
        else:
            need_resp = cap_mode == "strain"
            my_cap = np.zeros(n_list.size, dtype=float)
            mz_cap = np.zeros(n_list.size, dtype=float)
            print(f"build_NMM: capacityMode={cap_mode}, {n_list.size} levels x 2 analyses.")
            for i, n_val in enumerate(n_list):
                print(f"  N = {n_val:+.3e} ({i + 1}/{n_list.size})")
                p1, m1, f1 = _analyze(
                    self.sec_tag,
                    P=n_val,
                    axis=axis1,
                    max_phi=phiMax,
                    incr_phi=incrPhi,
                    stop_ratio=limitPeakRatio,
                    smart_analyze=smartAnalyze,
                    need_resp=need_resp,
                    debug=debug,
                )
                p2, m2, f2 = _analyze(
                    self.sec_tag,
                    P=n_val,
                    axis=axis2,
                    max_phi=phiMax,
                    incr_phi=incrPhi,
                    stop_ratio=limitPeakRatio,
                    smart_analyze=smartAnalyze,
                    need_resp=need_resp,
                    debug=debug,
                )
                my_cap[i] = abs(
                    _extract_moment_capacity(p1, m1, f1, cap_mode, peakDrop, matTag, threshold, targetPhi)[0]
                )
                mz_cap[i] = abs(
                    _extract_moment_capacity(p2, m2, f2, cap_mode, peakDrop, matTag, threshold, targetPhi)[0]
                )

        if np.any(~np.isfinite(my_cap)) or np.any(my_cap <= 0) or np.any(~np.isfinite(mz_cap)) or np.any(mz_cap <= 0):
            raise ValueError("All MyCap and MzCap entries must be positive and finite.")  # noqa: TRY003

        thetas = np.linspace(0.0, 2.0 * np.pi, int(nTheta), endpoint=False)
        cos_t = np.cos(thetas)[None, :]
        sin_t = np.sin(thetas)[None, :]
        denom = (cos_t / my_cap[:, None]) ** 2 + (sin_t / mz_cap[:, None]) ** 2
        radius = 1.0 / np.sqrt(denom)
        my_grid = radius * cos_t
        mz_grid = radius * sin_t

        my_grid = np.column_stack((my_grid, my_grid[:, 0]))
        mz_grid = np.column_stack((mz_grid, mz_grid[:, 0]))
        theta_closed = np.r_[thetas, thetas[0] + 2.0 * np.pi]

        self.NMMresult = {
            "N": n_list,
            "My": my_grid,
            "Mz": mz_grid,
            "thetas": theta_closed,
            "MyCap": my_cap,
            "MzCap": mz_cap,
            "MyPeak": my_cap,
            "MzPeak": mz_cap,
            "capMode": cap_mode,
        }
        print(f"build_NMM: done. ({0 if cap_mode == 'manual' else n_list.size * 2} OpenSees analyses)")
        return self.NMMresult

    build_nmm = build_NMM
    buildNMM = build_NMM

    def plot_NMM(
        self,
        normalize: bool = False,
        alpha: float = 0.5,
        colormap: str = "turbo",
        showSurface: bool = True,
        showPlanView: bool = True,
        showEnvelope: bool = True,
    ) -> dict[str, object]:
        """Plot N-My-Mz interaction results generated by :meth:`build_NMM`.

        Parameters
        ----------
        normalize : bool, optional
            Normalize plotted axes by their maximum absolute values.
        alpha : float, optional
            Transparency of the 3D surface.
        colormap : str, optional
            Matplotlib colormap name.
        showSurface, showPlanView, showEnvelope : bool, optional
            Toggle the 3D surface, My-Mz plan contours and uniaxial N-M
            capacity envelope figures.

        Returns
        -------
        dict
            Dictionary with keys ``surface``, ``plan`` and ``envelope``. Values
            are Matplotlib axes, or ``None`` for views that were not requested.
        """
        if not self.NMMresult:
            raise RuntimeError("Run build_NMM() before plot_NMM().")  # noqa: TRY003

        res = self.NMMresult
        n = np.asarray(res["N"], dtype=float)
        my = np.asarray(res["My"], dtype=float)
        mz = np.asarray(res["Mz"], dtype=float)
        my_cap = np.asarray(res["MyCap"], dtype=float)
        mz_cap = np.asarray(res["MzCap"], dtype=float)
        z = np.repeat(n[:, None], my.shape[1], axis=1)
        x_label, y_label, z_label = "$M_y$", "$M_z$", "$N$"

        if normalize:
            sx = _safe_scale(my)
            sy = _safe_scale(mz)
            sz = _safe_scale(n)
            my = my / sx
            mz = mz / sy
            z = z / sz
            my_cap = my_cap / sx
            mz_cap = mz_cap / sy
            n = n / sz
            x_label, y_label, z_label = "$M_y/max|M_y|$", "$M_z/max|M_z|$", "$N/max|N|$"

        cap_mode = str(res.get("capMode", "peak"))
        cmap = plt.get_cmap(colormap)
        colors = cmap(np.linspace(0.0, 1.0, len(n)))
        axs = {"surface": None, "plan": None, "envelope": None}

        if showSurface:
            fig = plt.figure(figsize=(9.2, 7.0))
            ax = fig.add_subplot(111, projection="3d")
            axs["surface"] = ax
            ax.plot_surface(my, mz, z, alpha=alpha, edgecolor="none", cmap=colormap)
            for i, color in enumerate(colors):
                ax.plot(my[i], mz[i], z[i], color=color, lw=1.2)
            step = max(1, my.shape[1] // 12)
            for j in range(0, my.shape[1], step):
                ax.plot(my[:, j], mz[:, j], z[:, j], color=(0, 0, 0, 0.22), lw=0.4)
            ax.set_xlabel(x_label)
            ax.set_ylabel(y_label)
            ax.set_zlabel(z_label)
            ax.set_title(f"N-My-Mz Interaction Surface [{cap_mode}]")
            ax.view_init(elev=30, azim=-45)

        if showPlanView:
            _, ax = plt.subplots(figsize=(5.2, 5.2))
            axs["plan"] = ax
            for i, color in enumerate(colors):
                ax.plot(my[i], mz[i], color=color, lw=1.4)
            ax.axhline(0.0, color="0.45", ls=":", lw=0.7)
            ax.axvline(0.0, color="0.45", ls=":", lw=0.7)
            ax.set_xlabel(x_label)
            ax.set_ylabel(y_label)
            ax.set_title(f"My-Mz Contours [{cap_mode}]")
            ax.set_aspect("equal", adjustable="box")
            ax.grid(True)

        if showEnvelope:
            _, ax = plt.subplots(figsize=(5.2, 3.8))
            axs["envelope"] = ax
            ax.plot(my_cap, n, "b-o", lw=1.5, ms=4, label="$M_y$ capacity")
            ax.plot(mz_cap, n, "r-s", lw=1.5, ms=4, label="$M_z$ capacity")
            ax.set_xlabel("Moment capacity")
            ax.set_ylabel(z_label)
            ax.set_title(f"Uniaxial N-M Envelope [{cap_mode}]")
            ax.legend()
            ax.grid(True)

        return axs

    plot_nmm = plot_NMM
    plotNMM = plot_NMM

    def _require_result(self) -> None:
        if self.phi is None or self.M is None:
            raise RuntimeError("No analysis result available. Run analyze() first.")  # noqa: TRY003


def _analyze(
    sec_tag: int,
    P: float = 0.0,
    axis: Axis = "y",
    max_phi: float = 0.05,
    incr_phi: float = 1e-4,
    stop_ratio: float = 0.8,
    smart_analyze: bool = True,
    cycle: bool = False,
    cycle_path: np.ndarray | list[float] | None = None,
    need_resp: bool = True,
    debug: bool = False,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    if incr_phi == 0:
        raise ValueError("incr_phi must be nonzero.")  # noqa: TRY003
    if stop_ratio <= 0:
        raise ValueError("stop_ratio must be positive.")  # noqa: TRY003

    _prepare_model(sec_tag)
    if P != 0:
        _apply_axial_load(P)

    dof = _get_dof(axis)
    _setup_unit_moment_load(dof)
    protocol = _build_protocol(max_phi, incr_phi, cycle, cycle_path)
    if protocol.size == 0:
        raise ValueError("Generated analysis protocol is empty.")  # noqa: TRY003
    max_abs_phi = np.max(np.abs(cycle_path)) if cycle and cycle_path is not None else abs(float(max_phi))

    phi, moment, resp = _run_protocol(
        protocol,
        dof,
        stop_ratio=stop_ratio,
        max_abs_phi=max_abs_phi,
        smart_analyze=smart_analyze,
        need_resp=need_resp,
        incr_phi=incr_phi,
        debug=debug,
    )
    return phi, moment, resp


def _prepare_model(sec_tag: int) -> None:
    try:
        existing_nodes = ops.getNodeTags()
    except Exception:
        existing_nodes = []

    if existing_nodes:
        _try_ops(ops.reset)
        _remove_prior_patterns()
        return

    ops.model("basic", "-ndm", 3, "-ndf", 6)
    ops.node(1, 0.0, 0.0, 0.0)
    ops.node(2, 0.0, 0.0, 0.0)
    ops.fix(1, 1, 1, 1, 1, 1, 1)
    ops.fix(2, 0, 1, 1, 1, 0, 0)
    ops.element("zeroLengthSection", 1, 1, 2, int(sec_tag))


def _remove_prior_patterns() -> None:
    for kind in ("loadPattern", "timeSeries"):
        for tag in (1, 2):
            _try_ops(ops.remove, kind, tag)


def _try_ops(func, *args) -> None:
    with suppress(Exception):
        func(*args)


def _apply_axial_load(p: float) -> None:
    ops.timeSeries("Linear", 1)
    ops.pattern("Plain", 1, 1)
    ops.load(2, float(p), 0.0, 0.0, 0.0, 0.0, 0.0)
    ops.wipeAnalysis()
    ops.system("BandGeneral")
    ops.constraints("Plain")
    ops.numberer("Plain")
    ops.test("NormDispIncr", 1.0e-10, 10, 3)
    ops.algorithm("Newton")
    ops.integrator("LoadControl", 0.1)
    ops.analysis("Static")
    ok = ops.analyze(10)
    if ok < 0:
        warn("Axial preload did not converge.", stacklevel=2)
    ops.loadConst("-time", 0.0)


def _setup_unit_moment_load(dof: int) -> None:
    load = [0.0] * 6
    load[dof - 1] = 1.0
    ops.timeSeries("Linear", 2)
    ops.pattern("Plain", 2, 2)
    ops.load(2, *load)


def _get_dof(axis: str) -> int:
    axis_map = {"y": 5, "z": 6}
    key = str(axis).lower()
    if key not in axis_map:
        raise ValueError("axis must be 'y' or 'z'.")  # noqa: TRY003
    return axis_map[key]


def _build_protocol(
    max_phi: float,
    incr_phi: float,
    cycle: bool,
    cycle_path: np.ndarray | list[float] | None,
) -> np.ndarray:
    if cycle and cycle_path is not None:
        path = np.asarray(cycle_path, dtype=float).reshape(-1)
        if path.size < 2:
            raise ValueError("cycle_path must contain at least two targets.")  # noqa: TRY003
        diffs = np.diff(path)
        steps = np.maximum(1, np.round(np.abs(diffs / incr_phi)).astype(int))
        return np.repeat(diffs / steps, steps)

    n_step = max(1, round(abs(float(max_phi) / incr_phi)))
    return np.full(n_step, float(max_phi) / n_step, dtype=float)


def _run_protocol(
    protocol: np.ndarray,
    dof: int,
    stop_ratio: float,
    max_abs_phi: float,
    smart_analyze: bool,
    need_resp: bool,
    incr_phi: float,
    debug: bool,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    n_prot = int(protocol.size)
    phi = np.zeros(n_prot + 1, dtype=float)
    moment = np.zeros(n_prot + 1, dtype=float)

    if need_resp:
        fd0 = _get_fiber_sec_data(1)
        resp = np.zeros((n_prot + 1, fd0.shape[0], 6), dtype=float)
    else:
        resp = np.empty((0, 0, 6), dtype=float)

    ops.wipeAnalysis()
    ops.system("BandGeneral")
    ops.constraints("Plain")
    ops.numberer("Plain")
    ops.test("EnergyIncr", 1.0e-10, 100, 3 if debug else 0)
    ops.algorithm("Newton")
    ops.integrator("DisplacementControl", 2, dof, float(protocol[0]))
    ops.analysis("Static")

    analysis = None
    if smart_analyze:
        analysis = SmartAnalyze(
            analysis_type="Static",
            testType="EnergyIncr",
            testTol=1.0e-10,
            testIterTimes=100,
            testPrintFlag=3 if debug else 0,
            tryAlterAlgoTypes=True,
            algoTypes=[40, 20],
            tryRelaxStep=True,
            relaxation=0.5,
            minStep=abs(float(incr_phi)) / 1e5,
            recordNormHistory=False,
            debugMode=debug,
        )
        analysis.set_total_steps(n_prot)

    ptr = 0
    peak_m = 0.0
    try:
        for i_step, step in enumerate(protocol, start=1):
            if smart_analyze:
                ok = analysis.StaticAnalyze(2, dof, float(step))
            else:
                ops.integrator("DisplacementControl", 2, dof, float(step))
                ok = ops.analyze(1)

            ptr += 1
            phi[ptr] = ops.nodeDisp(2, dof)
            moment[ptr] = ops.getLoadFactor(2)
            if need_resp:
                resp[ptr] = _get_fiber_sec_data(1)

            peak_m = max(peak_m, abs(moment[ptr]))
            if ptr >= 2:
                flip = (moment[ptr - 1] - moment[ptr]) * (phi[ptr - 1] - phi[ptr]) < 0
                decay = abs(moment[ptr]) <= peak_m * stop_ratio
                if (flip and decay) or abs(phi[ptr]) >= max_abs_phi:
                    break

            if ok < 0:
                warn(f"Step {i_step} did not converge; analysis terminated early.", stacklevel=2)
                break
    finally:
        if analysis is not None:
            analysis.close()

    return phi[: ptr + 1], moment[: ptr + 1], resp[: ptr + 1] if need_resp else resp


def _get_fiber_sec_data(ele_tag: int) -> np.ndarray:
    raw = np.asarray(ops.eleResponse(int(ele_tag), "section", "fiberData2"), dtype=float).reshape(-1)
    if raw.size == 0:
        return np.zeros((0, 6), dtype=float)
    if raw.size % 6 != 0:
        raise ValueError(f"fiberData2 length must be a multiple of 6, got {raw.size}.")  # noqa: TRY003
    return raw.reshape((-1, 6))


def _normalize_capacity_mode(capacity_mode: str) -> str:
    mode = str(capacity_mode).lower()
    if mode == "peakdrop":
        return mode
    valid = {"peak", "strain", "curvature", "manual"}
    if mode not in valid:
        raise ValueError("capacityMode must be one of: peak, peakDrop, strain, curvature, manual.")  # noqa: TRY003
    return mode


def _extract_moment_capacity(  # noqa: C901
    phi: np.ndarray,
    moment: np.ndarray,
    fd: np.ndarray | None,
    cap_mode: str = "peak",
    peak_drop: float = 0.20,
    mat_tag: int | list[int] | np.ndarray = 1,
    threshold: float | list[float] | np.ndarray = 0.0,
    target_phi: float | None = None,
) -> tuple[float, int]:
    phi = np.asarray(phi, dtype=float).reshape(-1)
    moment = np.asarray(moment, dtype=float).reshape(-1)
    if phi.size == 0 or moment.size == 0 or phi.size != moment.size:
        raise ValueError("phi and moment must be non-empty arrays with the same length.")  # noqa: TRY003

    n_step = phi.size
    abs_m = np.abs(moment)
    mode = _normalize_capacity_mode(cap_mode)

    if mode == "peak":
        idx = int(np.argmax(abs_m))
    elif mode == "peakdrop":
        drop = abs(float(peak_drop))
        if drop <= 0.0 or drop >= 1.0:
            raise ValueError("peak_drop must be in (0, 1).")  # noqa: TRY003
        idx_peak = int(np.argmax(abs_m))
        limit_m = (1.0 - drop) * abs_m[idx_peak]
        rel = np.flatnonzero(abs_m[idx_peak:] <= limit_m)
        if rel.size == 0:
            warn(f"Moment has not dropped {drop * 100:.1f}%; last step used.", stacklevel=2)
            idx = n_step - 1
        else:
            idx = idx_peak + int(rel[0])
    elif mode == "strain":
        if fd is None or fd.size == 0:
            raise ValueError('FiberData required for capacityMode="strain".')  # noqa: TRY003
        fd = np.asarray(fd, dtype=float)
        if fd.ndim != 3 or fd.shape[0] != n_step or fd.shape[2] < 6:
            raise ValueError("FiberData must have shape (nStep, nFiber, 6).")  # noqa: TRY003
        tags = np.atleast_1d(mat_tag).astype(float)
        thrs = np.atleast_1d(threshold).astype(float)
        if thrs.size == 1 and tags.size > 1:
            thrs = np.full(tags.size, thrs[0], dtype=float)
        if tags.size != thrs.size:
            raise ValueError("matTag and threshold must have the same length.")  # noqa: TRY003

        mat_id_row = fd[-1, :, 3]
        strain_all = fd[:, :, 5]
        idx_list = np.zeros(tags.size, dtype=int)
        for i, (tag, thr) in enumerate(zip(tags, thrs)):
            fiber_mask = np.abs(mat_id_row - tag) < 1e-6
            if not np.any(fiber_mask):
                warn(f"matTag {tag:g} not found; last step used.", stacklevel=2)
                idx_list[i] = n_step - 1
                continue
            sub = strain_all[:, fiber_mask]
            if thr >= 0:
                env = np.max(sub, axis=1)
                reached = np.flatnonzero(env >= thr)
            else:
                env = np.min(sub, axis=1)
                reached = np.flatnonzero(env <= thr)
            if reached.size == 0:
                warn(f"matTag {tag:g} strain {thr:.3g} not reached; last step used.", stacklevel=2)
                idx_list[i] = n_step - 1
            else:
                idx_list[i] = int(reached[0])
        idx = int(np.min(idx_list))
    elif mode == "curvature":
        if target_phi is None or not np.isfinite(target_phi) or target_phi == 0:
            raise ValueError('targetPhi must be nonzero for capacityMode="curvature".')  # noqa: TRY003
        idx = int(np.argmin(np.abs(phi - float(target_phi))))
    else:
        raise ValueError(f"Unsupported capacity mode: {cap_mode}.")  # noqa: TRY003

    idx = min(max(0, idx), n_step - 1)
    return float(moment[idx]), idx


def _bilinearize(
    phi: np.ndarray,
    moment: np.ndarray,
    phiy: float,
    my: float,
    phiu: float,
) -> tuple[float, float, int]:
    if phiy == 0 or my == 0 or phiu == 0:
        raise ValueError("phiy, My, and phiu must all be nonzero.")  # noqa: TRY003

    phi = np.asarray(phi, dtype=float).reshape(-1)
    moment = np.asarray(moment, dtype=float).reshape(-1)
    sign_phi = np.sign(phiu) or np.sign(phiy) or 1.0
    sign_m = np.sign(my) or sign_phi
    phi_y_abs = abs(float(phiy))
    my_abs = abs(float(my))
    phi_u_abs = abs(float(phiu))

    branch = phi >= 0 if sign_phi > 0 else phi <= 0
    if np.count_nonzero(branch) < 2:
        raise ValueError("Fewer than two points on the selected loading branch.")  # noqa: TRY003

    idx_branch = np.flatnonzero(branch)
    phi_branch = phi[idx_branch]
    moment_branch = moment[idx_branch]
    order = np.argsort(np.abs(phi_branch), kind="stable")
    phi_abs_sorted = np.abs(phi_branch[order])
    moment_abs_sorted = np.abs(moment_branch[order])
    idx_sorted = idx_branch[order]

    phi_abs, unique_idx = np.unique(phi_abs_sorted, return_index=True)
    moment_abs = moment_abs_sorted[unique_idx]
    idx_unique = idx_sorted[unique_idx]

    if phi_u_abs > phi_abs[-1]:
        warn("abs(phiu) exceeds available curvature range; last point used.", stacklevel=2)
        phi_u_abs = float(phi_abs[-1])

    idx_u = int(idx_unique[np.argmin(np.abs(phi_abs - phi_u_abs))])
    mask = phi_abs <= phi_u_abs
    phi_int = phi_abs[mask]
    moment_int = moment_abs[mask]
    if phi_int.size == 0 or phi_int[0] > 0:
        phi_int = np.r_[0.0, phi_int]
        moment_int = np.r_[0.0, moment_int]

    moment_u_abs = float(np.interp(phi_u_abs, phi_abs, moment_abs))
    if phi_int[-1] < phi_u_abs:
        phi_int = np.r_[phi_int, phi_u_abs]
        moment_int = np.r_[moment_int, moment_u_abs]
    else:
        phi_int[-1] = phi_u_abs
        moment_int[-1] = moment_u_abs

    phi_int, unique_idx = np.unique(phi_int, return_index=True)
    moment_int = moment_int[unique_idx]
    if phi_int.size < 2:
        raise ValueError("Not enough integration points for bilinearization.")  # noqa: TRY003

    area = trapezoid(moment_int, phi_int)
    stiffness = my_abs / phi_y_abs
    disc = (stiffness * phi_u_abs) ** 2 - 2.0 * stiffness * area
    tol = 1e-10 * max(1.0, (stiffness * phi_u_abs) ** 2)
    if disc < -tol:
        raise ValueError("Negative discriminant. Check phiy, My, phiu and selected branch.")  # noqa: TRY003
    disc = max(float(disc), 0.0)
    phi_eq_abs = (stiffness * phi_u_abs - np.sqrt(disc)) / stiffness
    moment_eq_abs = stiffness * phi_eq_abs
    return float(sign_phi * phi_eq_abs), float(sign_m * moment_eq_abs), idx_u


def _plot_bilinear(
    phi: np.ndarray,
    moment: np.ndarray,
    phiy: float,
    my: float,
    phiu: float,
    phi_eq: float,
    moment_eq: float,
    idx_u: int,
    ax=None,
):
    if ax is None:
        _, ax = plt.subplots(1, 1, figsize=(8, 5))
    sign_phi = np.sign(phiu) or 1.0
    branch = phi >= 0 if sign_phi > 0 else phi <= 0
    idx = np.flatnonzero(branch)
    idx = idx[np.argsort(np.abs(phi[idx]), kind="stable")]
    idx = idx[np.abs(phi[idx]) <= abs(phiu)]
    if idx.size == 0 or idx[0] != 0:
        plot_phi = np.r_[0.0, phi[idx]]
        plot_m = np.r_[0.0, moment[idx]]
    else:
        plot_phi = phi[idx]
        plot_m = moment[idx]

    ax.plot(plot_phi, plot_m, lw=1.5, c="#2529d8", label="M-phi curve")
    ax.plot([0.0, phiy, phi_eq, phiu], [0.0, my, moment_eq, moment_eq], lw=1.5, c="#de0f17", label="Bilinear")
    ax.plot(phiy, my, "o", ms=9, mec="black", mfc="#0099e5", label="Initial yield")
    ax.plot(phi_eq, moment_eq, "*", ms=12, mec="black", mfc="#ff4c4c", label="Equivalent yield")
    ax.axvline(phiu, color="#34bf49", ls="--", lw=0.8, label="$\\phi_u$")
    ax.set_title("Moment-Curvature Bilinear Approximation", fontsize=15)
    ax.set_xlabel("$\\phi$", fontsize=13)
    ax.set_ylabel("$M$", fontsize=13)
    ax.grid(True)
    ax.legend()
    return ax


def _safe_scale(values: np.ndarray) -> float:
    scale = float(np.nanmax(np.abs(values)))
    return scale if np.isfinite(scale) and scale > 0 else 1.0


def _get_center(ys, zs, areas):
    areas = np.asarray(areas, dtype=float)
    ys = np.asarray(ys, dtype=float)
    zs = np.asarray(zs, dtype=float)
    yo = np.sum(ys * areas) / np.sum(areas)
    zo = np.sum(zs * areas) / np.sum(areas)
    return yo, zo
